#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Biblioteca")]
public partial class BibliotecaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBibliotecari(Bibliotecari instance);
  partial void UpdateBibliotecari(Bibliotecari instance);
  partial void DeleteBibliotecari(Bibliotecari instance);
  partial void InsertCarti(Carti instance);
  partial void UpdateCarti(Carti instance);
  partial void DeleteCarti(Carti instance);
  partial void InsertMembri(Membri instance);
  partial void UpdateMembri(Membri instance);
  partial void DeleteMembri(Membri instance);
  partial void InsertReturnari(Returnari instance);
  partial void UpdateReturnari(Returnari instance);
  partial void DeleteReturnari(Returnari instance);
  partial void InsertRezervari(Rezervari instance);
  partial void UpdateRezervari(Rezervari instance);
  partial void DeleteRezervari(Rezervari instance);
  #endregion
	
	public BibliotecaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["conexiune"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Bibliotecari> Bibliotecaris
	{
		get
		{
			return this.GetTable<Bibliotecari>();
		}
	}
	
	public System.Data.Linq.Table<Carti> Cartis
	{
		get
		{
			return this.GetTable<Carti>();
		}
	}
	
	public System.Data.Linq.Table<Membri> Membris
	{
		get
		{
			return this.GetTable<Membri>();
		}
	}
	
	public System.Data.Linq.Table<Returnari> Returnaris
	{
		get
		{
			return this.GetTable<Returnari>();
		}
	}
	
	public System.Data.Linq.Table<Rezervari> Rezervaris
	{
		get
		{
			return this.GetTable<Rezervari>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bibliotecari")]
public partial class Bibliotecari : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Nume_utilizator;
	
	private string _Parola;
	
	private string _Nume_complet;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNume_utilizatorChanging(string value);
    partial void OnNume_utilizatorChanged();
    partial void OnParolaChanging(string value);
    partial void OnParolaChanged();
    partial void OnNume_completChanging(string value);
    partial void OnNume_completChanged();
    #endregion
	
	public Bibliotecari()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_utilizator", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Nume_utilizator
	{
		get
		{
			return this._Nume_utilizator;
		}
		set
		{
			if ((this._Nume_utilizator != value))
			{
				this.OnNume_utilizatorChanging(value);
				this.SendPropertyChanging();
				this._Nume_utilizator = value;
				this.SendPropertyChanged("Nume_utilizator");
				this.OnNume_utilizatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parola", DbType="VarChar(10)")]
	public string Parola
	{
		get
		{
			return this._Parola;
		}
		set
		{
			if ((this._Parola != value))
			{
				this.OnParolaChanging(value);
				this.SendPropertyChanging();
				this._Parola = value;
				this.SendPropertyChanged("Parola");
				this.OnParolaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_complet", DbType="VarChar(50)")]
	public string Nume_complet
	{
		get
		{
			return this._Nume_complet;
		}
		set
		{
			if ((this._Nume_complet != value))
			{
				this.OnNume_completChanging(value);
				this.SendPropertyChanging();
				this._Nume_complet = value;
				this.SendPropertyChanged("Nume_complet");
				this.OnNume_completChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carti")]
public partial class Carti : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_carte;
	
	private string _Titlu;
	
	private string _Autori;
	
	private string _Subiect;
	
	private string _Editura;
	
	private string _Disponibilitate;
	
	private System.Nullable<System.DateTime> _Data_adaugare;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_carteChanging(int value);
    partial void OnId_carteChanged();
    partial void OnTitluChanging(string value);
    partial void OnTitluChanged();
    partial void OnAutoriChanging(string value);
    partial void OnAutoriChanged();
    partial void OnSubiectChanging(string value);
    partial void OnSubiectChanged();
    partial void OnEdituraChanging(string value);
    partial void OnEdituraChanged();
    partial void OnDisponibilitateChanging(string value);
    partial void OnDisponibilitateChanged();
    partial void OnData_adaugareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_adaugareChanged();
    #endregion
	
	public Carti()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_carte", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id_carte
	{
		get
		{
			return this._Id_carte;
		}
		set
		{
			if ((this._Id_carte != value))
			{
				this.OnId_carteChanging(value);
				this.SendPropertyChanging();
				this._Id_carte = value;
				this.SendPropertyChanged("Id_carte");
				this.OnId_carteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titlu", DbType="VarChar(100)")]
	public string Titlu
	{
		get
		{
			return this._Titlu;
		}
		set
		{
			if ((this._Titlu != value))
			{
				this.OnTitluChanging(value);
				this.SendPropertyChanging();
				this._Titlu = value;
				this.SendPropertyChanged("Titlu");
				this.OnTitluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autori", DbType="VarChar(100)")]
	public string Autori
	{
		get
		{
			return this._Autori;
		}
		set
		{
			if ((this._Autori != value))
			{
				this.OnAutoriChanging(value);
				this.SendPropertyChanging();
				this._Autori = value;
				this.SendPropertyChanged("Autori");
				this.OnAutoriChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subiect", DbType="VarChar(50)")]
	public string Subiect
	{
		get
		{
			return this._Subiect;
		}
		set
		{
			if ((this._Subiect != value))
			{
				this.OnSubiectChanging(value);
				this.SendPropertyChanging();
				this._Subiect = value;
				this.SendPropertyChanged("Subiect");
				this.OnSubiectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editura", DbType="VarChar(50)")]
	public string Editura
	{
		get
		{
			return this._Editura;
		}
		set
		{
			if ((this._Editura != value))
			{
				this.OnEdituraChanging(value);
				this.SendPropertyChanging();
				this._Editura = value;
				this.SendPropertyChanged("Editura");
				this.OnEdituraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disponibilitate", DbType="Char(2)")]
	public string Disponibilitate
	{
		get
		{
			return this._Disponibilitate;
		}
		set
		{
			if ((this._Disponibilitate != value))
			{
				this.OnDisponibilitateChanging(value);
				this.SendPropertyChanging();
				this._Disponibilitate = value;
				this.SendPropertyChanged("Disponibilitate");
				this.OnDisponibilitateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_adaugare", DbType="DateTime")]
	public System.Nullable<System.DateTime> Data_adaugare
	{
		get
		{
			return this._Data_adaugare;
		}
		set
		{
			if ((this._Data_adaugare != value))
			{
				this.OnData_adaugareChanging(value);
				this.SendPropertyChanging();
				this._Data_adaugare = value;
				this.SendPropertyChanged("Data_adaugare");
				this.OnData_adaugareChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Membri")]
public partial class Membri : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_membru;
	
	private string _Nume_membru;
	
	private string _Adresa_membru;
	
	private System.Nullable<System.DateTime> _Data_inregistrare;
	
	private string _Email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_membruChanging(int value);
    partial void OnId_membruChanged();
    partial void OnNume_membruChanging(string value);
    partial void OnNume_membruChanged();
    partial void OnAdresa_membruChanging(string value);
    partial void OnAdresa_membruChanged();
    partial void OnData_inregistrareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_inregistrareChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
	
	public Membri()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_membru", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id_membru
	{
		get
		{
			return this._Id_membru;
		}
		set
		{
			if ((this._Id_membru != value))
			{
				this.OnId_membruChanging(value);
				this.SendPropertyChanging();
				this._Id_membru = value;
				this.SendPropertyChanged("Id_membru");
				this.OnId_membruChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_membru", DbType="VarChar(50)")]
	public string Nume_membru
	{
		get
		{
			return this._Nume_membru;
		}
		set
		{
			if ((this._Nume_membru != value))
			{
				this.OnNume_membruChanging(value);
				this.SendPropertyChanging();
				this._Nume_membru = value;
				this.SendPropertyChanged("Nume_membru");
				this.OnNume_membruChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa_membru", DbType="VarChar(100)")]
	public string Adresa_membru
	{
		get
		{
			return this._Adresa_membru;
		}
		set
		{
			if ((this._Adresa_membru != value))
			{
				this.OnAdresa_membruChanging(value);
				this.SendPropertyChanging();
				this._Adresa_membru = value;
				this.SendPropertyChanged("Adresa_membru");
				this.OnAdresa_membruChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_inregistrare", DbType="DateTime")]
	public System.Nullable<System.DateTime> Data_inregistrare
	{
		get
		{
			return this._Data_inregistrare;
		}
		set
		{
			if ((this._Data_inregistrare != value))
			{
				this.OnData_inregistrareChanging(value);
				this.SendPropertyChanging();
				this._Data_inregistrare = value;
				this.SendPropertyChanged("Data_inregistrare");
				this.OnData_inregistrareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Returnari")]
public partial class Returnari : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_carte;
	
	private System.Nullable<int> _Id_membru;
	
	private System.Nullable<System.DateTime> _Data_rezervare;
	
	private System.Nullable<System.DateTime> _Data_returnare;
	
	private string _Bibliotecar_rezervare;
	
	private string _Bibliotecar_returnare;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_carteChanging(int value);
    partial void OnId_carteChanged();
    partial void OnId_membruChanging(System.Nullable<int> value);
    partial void OnId_membruChanged();
    partial void OnData_rezervareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_rezervareChanged();
    partial void OnData_returnareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_returnareChanged();
    partial void OnBibliotecar_rezervareChanging(string value);
    partial void OnBibliotecar_rezervareChanged();
    partial void OnBibliotecar_returnareChanging(string value);
    partial void OnBibliotecar_returnareChanged();
    #endregion
	
	public Returnari()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_carte", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id_carte
	{
		get
		{
			return this._Id_carte;
		}
		set
		{
			if ((this._Id_carte != value))
			{
				this.OnId_carteChanging(value);
				this.SendPropertyChanging();
				this._Id_carte = value;
				this.SendPropertyChanged("Id_carte");
				this.OnId_carteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_membru", DbType="Int")]
	public System.Nullable<int> Id_membru
	{
		get
		{
			return this._Id_membru;
		}
		set
		{
			if ((this._Id_membru != value))
			{
				this.OnId_membruChanging(value);
				this.SendPropertyChanging();
				this._Id_membru = value;
				this.SendPropertyChanged("Id_membru");
				this.OnId_membruChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_rezervare", DbType="DateTime")]
	public System.Nullable<System.DateTime> Data_rezervare
	{
		get
		{
			return this._Data_rezervare;
		}
		set
		{
			if ((this._Data_rezervare != value))
			{
				this.OnData_rezervareChanging(value);
				this.SendPropertyChanging();
				this._Data_rezervare = value;
				this.SendPropertyChanged("Data_rezervare");
				this.OnData_rezervareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_returnare", DbType="DateTime")]
	public System.Nullable<System.DateTime> Data_returnare
	{
		get
		{
			return this._Data_returnare;
		}
		set
		{
			if ((this._Data_returnare != value))
			{
				this.OnData_returnareChanging(value);
				this.SendPropertyChanging();
				this._Data_returnare = value;
				this.SendPropertyChanged("Data_returnare");
				this.OnData_returnareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bibliotecar_rezervare", DbType="VarChar(10)")]
	public string Bibliotecar_rezervare
	{
		get
		{
			return this._Bibliotecar_rezervare;
		}
		set
		{
			if ((this._Bibliotecar_rezervare != value))
			{
				this.OnBibliotecar_rezervareChanging(value);
				this.SendPropertyChanging();
				this._Bibliotecar_rezervare = value;
				this.SendPropertyChanged("Bibliotecar_rezervare");
				this.OnBibliotecar_rezervareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bibliotecar_returnare", DbType="VarChar(10)")]
	public string Bibliotecar_returnare
	{
		get
		{
			return this._Bibliotecar_returnare;
		}
		set
		{
			if ((this._Bibliotecar_returnare != value))
			{
				this.OnBibliotecar_returnareChanging(value);
				this.SendPropertyChanging();
				this._Bibliotecar_returnare = value;
				this.SendPropertyChanged("Bibliotecar_returnare");
				this.OnBibliotecar_returnareChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rezervari")]
public partial class Rezervari : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_carte;
	
	private System.Nullable<int> _Id_membru;
	
	private System.Nullable<System.DateTime> _Data_rezervare;
	
	private string _Bibliotecar;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_carteChanging(int value);
    partial void OnId_carteChanged();
    partial void OnId_membruChanging(System.Nullable<int> value);
    partial void OnId_membruChanged();
    partial void OnData_rezervareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_rezervareChanged();
    partial void OnBibliotecarChanging(string value);
    partial void OnBibliotecarChanged();
    #endregion
	
	public Rezervari()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_carte", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id_carte
	{
		get
		{
			return this._Id_carte;
		}
		set
		{
			if ((this._Id_carte != value))
			{
				this.OnId_carteChanging(value);
				this.SendPropertyChanging();
				this._Id_carte = value;
				this.SendPropertyChanged("Id_carte");
				this.OnId_carteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_membru", DbType="Int")]
	public System.Nullable<int> Id_membru
	{
		get
		{
			return this._Id_membru;
		}
		set
		{
			if ((this._Id_membru != value))
			{
				this.OnId_membruChanging(value);
				this.SendPropertyChanging();
				this._Id_membru = value;
				this.SendPropertyChanged("Id_membru");
				this.OnId_membruChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_rezervare", DbType="DateTime")]
	public System.Nullable<System.DateTime> Data_rezervare
	{
		get
		{
			return this._Data_rezervare;
		}
		set
		{
			if ((this._Data_rezervare != value))
			{
				this.OnData_rezervareChanging(value);
				this.SendPropertyChanging();
				this._Data_rezervare = value;
				this.SendPropertyChanged("Data_rezervare");
				this.OnData_rezervareChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bibliotecar", DbType="VarChar(10)")]
	public string Bibliotecar
	{
		get
		{
			return this._Bibliotecar;
		}
		set
		{
			if ((this._Bibliotecar != value))
			{
				this.OnBibliotecarChanging(value);
				this.SendPropertyChanging();
				this._Bibliotecar = value;
				this.SendPropertyChanged("Bibliotecar");
				this.OnBibliotecarChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
